spring.application.name=ctfbackend

# PostgreSQL settings
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ctf}
spring.datasource.username=ctfuser
spring.datasource.password=ctfpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.sql.init.mode=always

# University LDAP
spring.ldap.urls=ldaps://ldap.technikum-wien.at:636
spring.ldap.base=ou=people,dc=technikum-wien,dc=at
# Logging
logging.level.org.springframework.security=DEBUG

# File upload settings

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

challenges.base.path=/opt/ctf/backend/challenges