version: "3.9"

networks:
  ctf-network:
    driver: bridge
    name: ctf-network

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
      POSTGRES_DB: ctf
    ports:
      - "5432:5432"
    networks:
      - ctf-network
    volumes:
      - pgdata-test:/var/lib/postgresql/data

volumes:
  pgdata-test:
