sonar.projectKey=InnoLab-Project
sonar.projectName=InnoLab Project

sonar.sources=ctf-frontend/app,ctf-frontend/components,ctf-frontend/lib,ctf-backend/src/main/java
sonar.tests=ctf-frontend/src/test,ctf-frontend/lib/api/_tests_,ctf-frontend/lib/hooks/_test_,ctf-backend/src/test/java
sonar.exclusions=**/node_modules/**,**/target/**,**/coverage/**,**/.next/**,**/dist/**,**/test_ignored/**,**/*.class,ctf-frontend/**/*.test.ts,ctf-frontend/**/*.test.tsx,ctf-frontend/**/_test_/**,ctf-frontend/**/_tests_/**
sonar.test.inclusions=ctf-frontend/**/*.test.ts,ctf-frontend/**/*.test.tsx,ctf-backend/src/test/**/*.java

sonar.javascript.lcov.reportPaths=ctf-frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=ctf-backend/target/site/jacoco/jacoco.xml
sonar.java.binaries=ctf-backend/target/classes
sonar.java.test.binaries=ctf-backend/target/test-classes
